name: Main merge and push

on:
  #  workflow_dispatch:
  pull_request_target:
    branches: [ main ]
    types:
      - closed
  push:
    branches: [ main ]

env:
    VER_MAJOR: 23
    VER_MINOR: 4
    VER_PATCH: 0

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          include-prerelease: true

      - name: Install dependencies
        run: dotnet restore mTeller.sln

  build:
    needs: test
    if: github.event.action != 'labeled' || contains(github.event.pull_request.labels.*.name, 'mBUILD!')
    runs-on: ubuntu-latest

    steps:
      - name: Remove build label if set
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        if: github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'mBUILD!')
        with:
          github_token: ${{ secrets.github_token }}
          labels: 'mBUILD!'
        
      - name: Repo Checkout
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0

      - name: Set short git commit SHA
        id: vars
        run: |
            calculatedSha=$(git rev-parse --short ${{ github.sha }})
            echo "short_sha=$calculatedSha" >> $GITHUB_OUTPUT

      - name: Generate version
        id: mteller
        run: |
          VERFULL=${{ env.VER_MAJOR }}.${{ env.VER_MINOR }}.${{ env.VER_PATCH }}+${{ steps.vars.outputs.short_sha }}.${{ github.run_number }}
          echo 'generated version: '$VERFULL
          echo "ver-full=$VERFULL" >> $GITHUB_OUTPUT

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          include-prerelease: true

      - name: Install dependencies
        run: dotnet restore mTeller.sln

      - name: Build
        run: dotnet build mTeller.sln --configuration Release /p:Version=${{ steps.mteller.outputs.ver-full }} --no-restore
       
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.MT_DH_USERNAME }}
          password: ${{ secrets.MT_DH_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: mtellergh/mteller-web:latest