name: PR Build

on:
  #  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, ready_for_review, labeled ]

env:
    VER_MAJOR: 23
    VER_MINOR: 4
    VER_PATCH: ${{ github.event.number }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          include-prerelease: true

      - name: Install dependencies
        run: dotnet restore mTeller.sln

      - name: Test
        run: dotnet test mTeller.sln --configuration Release --no-restore

  build:
    needs: test
    if: github.event.action != 'labeled' || contains(github.event.pull_request.labels.*.name, 'mBUILD!')
    runs-on: ubuntu-latest

    steps:
      - name: Remove build label if set
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        if: github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'mBUILD!')
        with:
          github_token: ${{ secrets.github_token }}
          labels: 'mBUILD!'
        
      - name: Repo Checkout
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0

      - name: Set short git commit SHA
        id: vars
        run: |
            calculatedSha=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})
            echo "short_sha=$calculatedSha" >> $GITHUB_OUTPUT

      - name: Generate version
        id: mteller
        run: |
          VERFULL=${{ env.VER_MAJOR }}.${{ env.VER_MINOR }}.${{ env.VER_PATCH }}+${{ steps.vars.outputs.short_sha }}.${{ github.run_number }}
          VERCORE=${{ env.VER_MAJOR }}.${{ env.VER_MINOR }}.${{ env.VER_PATCH }}
          echo core: $VER_CORE
          echo "ver-core=$VERCORE" >> $GITHUB_OUTPUT
          echo 'generated version: '$VER_FULL
          echo "ver-full=$VERFULL" >> $GITHUB_OUTPUT

      - name: Echo version
        id: version
        run: |
             echo "${{ steps.mteller.outputs.ver-full }}"
             echo "${{ steps.mteller.outputs.ver-core }}"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          include-prerelease: true

      - name: Install dependencies
        run: dotnet restore mTeller.sln

      - name: Build
        run: dotnet build mTeller.sln --configuration Release /p:Version=${{ steps.mteller.outputs.ver-core }}-pr.${{ github.event.number }} --no-restore

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.MT_DH_USERNAME }}
          password: ${{ secrets.MT_DH_PASSWORD }}
      -
        name: Build and push
        # only build and push container if label mBUILD
        if: github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'mBUILD!')

        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: mtellergh/mteller-web:pr.${{ github.event.number }}

  Add_dod_comments:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Add comment to PR
          env:
            URL: ${{ github.event.pull_request.comments_url }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            curl \
              -X POST \
              $URL \
              -H "Content-Type: application/json" \
              -H "Authorization: token $GITHUB_TOKEN" \
              --data '{ "body": "**Review** \nAs part of our definition-of-done, the following steps need to be reviewed.\n\n- [ ] Min Unit Test coverage- 40%\n- [ ] API tests are written\n- [ ] Code comments written\n- [ ] Swagger documentation written/updated\n- [ ] Error handling enabled\n- [ ] Code review done\n- [ ] Code smells fixed"}'
  